Testing catch block with Type Error PASSED!
