Testing Nested try block with multiple catch block inside the finally block of the outer try block PASSED!
Testing Nested try block with multiple catch block inside the finally block of the inner try block PASSED!
